name: publish
on: [push]
jobs:
       publish-tesseract-ocr-web-image:
              runs-on: ubuntu-latest
              steps:
                     - uses: actions/checkout@v2
                     - name: Login to GitHub Container Registry
                       uses: docker/login-action@v1
                       with:
                            registry: ghcr.io
                            username: ${{ github.actor }}
                            password: ${{ secrets.GITHUB_TOKEN }}
                     - name: Build the tesseract-ocr-web Docker image
                       run: |
                            docker build . --tag ghcr.io/santhoshtr/tesseract-ocr-web:latest
                            docker push ghcr.io/santhoshtr/tesseract-ocr-web:latest
